services:
  acme-gateway-go:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    container_name: acme-gateway-go
    restart: on-failure
    env_file: ../.env
    volumes:
      - ../:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 48952:48952
    cap_add:
      - NET_ADMIN