services:
  acme-gateway-go:
    image: ghcr.io/vhvy/acme-gateway-go:master
    container_name: acme-gateway-go
    restart: unless-stopped
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - GATEWAY_TOKEN=${GATEWAY_TOKEN}
    volumes:
      - ./data:/app/data
       - /etc/localtime:/etc/localtime:ro
    ports:
      - 48952:48952
    dns:
      - 127.0.0.1