FROM golang:1.25.2-alpine3.22 AS builder

WORKDIR /app

RUN apk update
RUN apk --no-cache add ca-certificates iptables

COPY go.mod go.sum ./

RUN go mod download
RUN go install github.com/air-verse/air@latest

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["air", "-c", ".air.toml"]