FROM golang:1.25.2-alpine3.22 AS builder

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY go.mod go.sum ./

RUN go mod download
RUN go install github.com/air-verse/air@latest

CMD ["air", "-c", ".air.toml"]