# ------------- build -------------------
FROM golang:1.25.2-alpine3.22 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app .

# ------------- runtime -----------------

FROM alpine:3.22

WORKDIR /app
RUN apk update
RUN apk --no-cache add ca-certificates iptables
COPY --from=builder /app/app .

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["./app"]